import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider/QueryProvider";


const montserrat = Cairo({
  weight: ["200", "300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "CareBook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
        cz-shortcut-listen="true"
      >
        <QueryProvider>
          {children}
          <Toaster position="top-right"/>
        </QueryProvider>
      </body>
    </html>
  );
}
